spring:
  application.name: build-scheduler
  jackson.default-property-inclusion: NON_EMPTY

github:
  webhook-secret: ${GITHUB_WEBHOOK_SECRET:none}
  app-id: ${GITHUB_APP_ID:none}
  app-key: ${GITHUB_APP_KEY:none}
  orga-pat: ${GITHUB_ORGA_PAT:none}
  job-url: ${GITHUB_JOB_URL:https://api.github.com/repos/deploy-my-app/build-app/actions/workflows/dispatcher.yml/dispatches}